// Code generated by protoc-gen-go.
// source: github.com/micro/trace-srv/proto/trace/trace.proto
// DO NOT EDIT!

/*
Package go_micro_srv_trace_trace is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/trace-srv/proto/trace/trace.proto

It has these top-level messages:
	CreateRequest
	CreateResponse
	ReadRequest
	ReadResponse
	DeleteRequest
	DeleteResponse
	SearchRequest
	SearchResponse
*/
package go_micro_srv_trace_trace

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import go_micro_os_trace "github.com/micro/go-os/trace/proto"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateRequest struct {
	Span *go_micro_os_trace.Span `protobuf:"bytes,1,opt,name=span" json:"span,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateRequest) GetSpan() *go_micro_os_trace.Span {
	if m != nil {
		return m.Span
	}
	return nil
}

type CreateResponse struct {
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ReadRequest struct {
	// trace id
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ReadResponse struct {
	Spans []*go_micro_os_trace.Span `protobuf:"bytes,1,rep,name=spans" json:"spans,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadResponse) GetSpans() []*go_micro_os_trace.Span {
	if m != nil {
		return m.Spans
	}
	return nil
}

type DeleteRequest struct {
	// trace id
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type SearchRequest struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Limit   int64  `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
	Offset  int64  `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
	Reverse bool   `protobuf:"varint,4,opt,name=reverse" json:"reverse,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type SearchResponse struct {
	Spans []*go_micro_os_trace.Span `protobuf:"bytes,1,rep,name=spans" json:"spans,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SearchResponse) GetSpans() []*go_micro_os_trace.Span {
	if m != nil {
		return m.Spans
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "go.micro.srv.trace.trace.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "go.micro.srv.trace.trace.CreateResponse")
	proto.RegisterType((*ReadRequest)(nil), "go.micro.srv.trace.trace.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "go.micro.srv.trace.trace.ReadResponse")
	proto.RegisterType((*DeleteRequest)(nil), "go.micro.srv.trace.trace.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "go.micro.srv.trace.trace.DeleteResponse")
	proto.RegisterType((*SearchRequest)(nil), "go.micro.srv.trace.trace.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "go.micro.srv.trace.trace.SearchResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Trace service

type TraceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error)
}

type traceClient struct {
	c           client.Client
	serviceName string
}

func NewTraceClient(serviceName string, c client.Client) TraceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.trace.trace"
	}
	return &traceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *traceClient) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Trace.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traceClient) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Trace.Read", in)
	out := new(ReadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Trace.Delete", in)
	out := new(DeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traceClient) Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Trace.Search", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Trace service

type TraceHandler interface {
	Create(context.Context, *CreateRequest, *CreateResponse) error
	Read(context.Context, *ReadRequest, *ReadResponse) error
	Delete(context.Context, *DeleteRequest, *DeleteResponse) error
	Search(context.Context, *SearchRequest, *SearchResponse) error
}

func RegisterTraceHandler(s server.Server, hdlr TraceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Trace{hdlr}, opts...))
}

type Trace struct {
	TraceHandler
}

func (h *Trace) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.TraceHandler.Create(ctx, in, out)
}

func (h *Trace) Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error {
	return h.TraceHandler.Read(ctx, in, out)
}

func (h *Trace) Delete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error {
	return h.TraceHandler.Delete(ctx, in, out)
}

func (h *Trace) Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error {
	return h.TraceHandler.Search(ctx, in, out)
}

func init() { proto.RegisterFile("github.com/micro/trace-srv/proto/trace/trace.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x93, 0x5d, 0x4b, 0x32, 0x41,
	0x14, 0xc7, 0x7d, 0x59, 0x7d, 0x9e, 0x8e, 0x29, 0x31, 0x44, 0x2d, 0x42, 0x14, 0x03, 0x95, 0x10,
	0x8e, 0x60, 0xb7, 0x45, 0x17, 0xf5, 0x09, 0xd6, 0xa0, 0xab, 0x2e, 0xd6, 0xf5, 0xa8, 0x4b, 0xae,
	0x63, 0x33, 0xa3, 0xdf, 0x3e, 0x68, 0x9c, 0x17, 0x73, 0x0d, 0x57, 0xe8, 0x66, 0x98, 0x73, 0xce,
	0xff, 0xfc, 0xce, 0xd9, 0xf9, 0xb3, 0xd0, 0x9f, 0xa4, 0x6a, 0xba, 0x1c, 0xb2, 0x84, 0x67, 0xbd,
	0x2c, 0x4d, 0x04, 0xef, 0x29, 0x11, 0x27, 0xd8, 0x95, 0x62, 0xd5, 0x5b, 0x08, 0xae, 0x5c, 0x6c,
	0x4f, 0x66, 0x32, 0x24, 0x9c, 0x70, 0x66, 0xb4, 0x4c, 0xab, 0x98, 0xad, 0x98, 0xb3, 0xcd, 0x7e,
	0xd1, 0x26, 0xbc, 0xcb, 0xa5, 0x63, 0x6c, 0xf1, 0x2c, 0x89, 0x3e, 0x40, 0xf3, 0x59, 0x60, 0xac,
	0x30, 0xc2, 0xcf, 0x25, 0x4a, 0x45, 0xee, 0x20, 0x90, 0x8b, 0x78, 0x1e, 0x96, 0xaf, 0xca, 0x9d,
	0x46, 0xff, 0x9c, 0x6d, 0x26, 0x71, 0xe9, 0x06, 0x0d, 0x74, 0x39, 0x32, 0x22, 0x7a, 0x02, 0x2d,
	0xdf, 0x2d, 0x17, 0x7c, 0x2e, 0x91, 0x5e, 0x40, 0x23, 0xc2, 0x78, 0xe4, 0x69, 0x2d, 0xa8, 0xa4,
	0x23, 0xc3, 0x3a, 0x8a, 0xf4, 0x8d, 0x3e, 0xc2, 0xb1, 0x2d, 0x5b, 0x39, 0xe9, 0x42, 0x6d, 0x0d,
	0x92, 0x5a, 0x52, 0x2d, 0x1a, 0x67, 0x55, 0xf4, 0x12, 0x9a, 0x2f, 0x38, 0xc3, 0x9f, 0x6d, 0x77,
	0xf9, 0x7a, 0x21, 0x2f, 0x70, 0x0b, 0x7d, 0x40, 0x73, 0x80, 0xb1, 0x48, 0xa6, 0xbe, 0x85, 0x40,
	0x30, 0x8f, 0x33, 0x74, 0x4d, 0xe6, 0x4e, 0x4e, 0xa1, 0x36, 0x4b, 0xb3, 0x54, 0x85, 0x15, 0x9d,
	0xac, 0x46, 0x36, 0x20, 0x67, 0x50, 0xe7, 0xe3, 0xb1, 0x44, 0x15, 0x56, 0x4d, 0xda, 0x45, 0x24,
	0x84, 0x7f, 0x02, 0x57, 0x28, 0x24, 0x86, 0x81, 0x2e, 0xfc, 0x8f, 0x7c, 0x48, 0x9f, 0xa0, 0xe5,
	0x87, 0xfd, 0xe9, 0x03, 0xfb, 0x5f, 0x15, 0xa8, 0xbd, 0xae, 0xb3, 0xe4, 0x1d, 0xea, 0xf6, 0x69,
	0xc9, 0x2d, 0xdb, 0xe7, 0x36, 0xcb, 0x59, 0xd7, 0xee, 0x1c, 0x16, 0xba, 0x47, 0x29, 0x91, 0x37,
	0x08, 0xd6, 0x46, 0x90, 0xeb, 0xfd, 0x3d, 0x5b, 0x3e, 0xb6, 0x6f, 0x0e, 0xc9, 0x36, 0x60, 0xbd,
	0xb7, 0x75, 0xa0, 0x68, 0xef, 0x9c, 0x89, 0x45, 0x7b, 0xef, 0x98, 0x69, 0xf0, 0xf6, 0x85, 0x8b,
	0xf0, 0x39, 0xc3, 0x8b, 0xf0, 0x79, 0xb3, 0x68, 0x69, 0x58, 0x37, 0x7f, 0xc5, 0xfd, 0x77, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x70, 0x05, 0x39, 0x0b, 0x95, 0x03, 0x00, 0x00,
}
