// Code generated by protoc-gen-go.
// source: github.com/micro/trace-srv/proto/trace/trace.proto
// DO NOT EDIT!

/*
Package trace is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/trace-srv/proto/trace/trace.proto

It has these top-level messages:
	CreateRequest
	CreateResponse
	ReadRequest
	ReadResponse
*/
package trace

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import trace1 "github.com/micro/go-platform/trace/proto"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CreateRequest struct {
	Span *trace1.Span `protobuf:"bytes,1,opt,name=span" json:"span,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateRequest) GetSpan() *trace1.Span {
	if m != nil {
		return m.Span
	}
	return nil
}

type CreateResponse struct {
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ReadRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ReadResponse struct {
	Spans []*trace1.Span `protobuf:"bytes,1,rep,name=spans" json:"spans,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadResponse) GetSpans() []*trace1.Span {
	if m != nil {
		return m.Spans
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "CreateResponse")
	proto.RegisterType((*ReadRequest)(nil), "ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "ReadResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Trace service

type TraceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error)
}

type traceClient struct {
	c           client.Client
	serviceName string
}

func NewTraceClient(serviceName string, c client.Client) TraceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "trace"
	}
	return &traceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *traceClient) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Trace.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traceClient) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Trace.Read", in)
	out := new(ReadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Trace service

type TraceHandler interface {
	Create(context.Context, *CreateRequest, *CreateResponse) error
	Read(context.Context, *ReadRequest, *ReadResponse) error
}

func RegisterTraceHandler(s server.Server, hdlr TraceHandler) {
	s.Handle(s.NewHandler(&Trace{hdlr}))
}

type Trace struct {
	TraceHandler
}

func (h *Trace) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.TraceHandler.Create(ctx, in, out)
}

func (h *Trace) Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error {
	return h.TraceHandler.Read(ctx, in, out)
}

var fileDescriptor0 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x32, 0x4a, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0xcd, 0x4c, 0x2e, 0xca, 0xd7, 0x2f, 0x29, 0x4a,
	0x4c, 0x4e, 0xd5, 0x2d, 0x2e, 0x2a, 0xd3, 0x2f, 0x28, 0xca, 0x2f, 0x81, 0xf2, 0x21, 0xa4, 0x1e,
	0x58, 0x44, 0xca, 0x04, 0x43, 0x4f, 0x7a, 0xbe, 0x6e, 0x41, 0x4e, 0x62, 0x49, 0x5a, 0x7e, 0x51,
	0x2e, 0x54, 0x3d, 0x92, 0x5e, 0x88, 0x2e, 0x25, 0x15, 0x2e, 0x5e, 0xe7, 0xa2, 0xd4, 0xc4, 0x92,
	0xd4, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x61, 0x2e, 0x96, 0xe2, 0x82, 0xc4, 0x3c,
	0x09, 0x46, 0x05, 0x46, 0x0d, 0x6e, 0x23, 0x56, 0xbd, 0x60, 0x20, 0x47, 0x49, 0x80, 0x8b, 0x0f,
	0xa6, 0xaa, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x49, 0x92, 0x8b, 0x3b, 0x28, 0x35, 0x31, 0x05,
	0xa6, 0x8b, 0x8b, 0x8b, 0x29, 0x33, 0x05, 0xac, 0x87, 0x13, 0x68, 0x24, 0x0f, 0x44, 0x0a, 0xa2,
	0x54, 0x48, 0x84, 0x8b, 0x15, 0x64, 0x62, 0x31, 0x50, 0x9a, 0x19, 0x6e, 0xa4, 0x51, 0x34, 0x17,
	0x6b, 0x08, 0xc8, 0x1d, 0x42, 0xda, 0x5c, 0x6c, 0x10, 0xb3, 0x85, 0xf8, 0xf4, 0x50, 0x9c, 0x22,
	0xc5, 0xaf, 0x87, 0x66, 0x29, 0x83, 0x90, 0x2a, 0x17, 0x0b, 0xc8, 0x6c, 0x21, 0x1e, 0x3d, 0x24,
	0xdb, 0xa5, 0x78, 0xf5, 0x90, 0x2d, 0x54, 0x62, 0x48, 0x62, 0x03, 0x7b, 0xce, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0x58, 0x68, 0xe5, 0x4c, 0x48, 0x01, 0x00, 0x00,
}
