// Code generated by protoc-gen-go.
// source: github.com/micro/trace-srv/proto/trace/trace.proto
// DO NOT EDIT!

/*
Package trace is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/trace-srv/proto/trace/trace.proto

It has these top-level messages:
	CreateRequest
	CreateResponse
	ReadRequest
	ReadResponse
	DeleteRequest
	DeleteResponse
	SearchRequest
	SearchResponse
*/
package trace

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import trace1 "github.com/micro/go-platform/trace/proto"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type CreateRequest struct {
	Span *trace1.Span `protobuf:"bytes,1,opt,name=span" json:"span,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateRequest) GetSpan() *trace1.Span {
	if m != nil {
		return m.Span
	}
	return nil
}

type CreateResponse struct {
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ReadRequest struct {
	// trace id
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ReadResponse struct {
	Spans []*trace1.Span `protobuf:"bytes,1,rep,name=spans" json:"spans,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadResponse) GetSpans() []*trace1.Span {
	if m != nil {
		return m.Spans
	}
	return nil
}

type DeleteRequest struct {
	// trace id
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type SearchRequest struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Limit   int64  `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
	Offset  int64  `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
	Reverse bool   `protobuf:"varint,4,opt,name=reverse" json:"reverse,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type SearchResponse struct {
	Spans []*trace1.Span `protobuf:"bytes,1,rep,name=spans" json:"spans,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SearchResponse) GetSpans() []*trace1.Span {
	if m != nil {
		return m.Spans
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "CreateResponse")
	proto.RegisterType((*ReadRequest)(nil), "ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "ReadResponse")
	proto.RegisterType((*DeleteRequest)(nil), "DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "DeleteResponse")
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "SearchResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Trace service

type TraceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error)
}

type traceClient struct {
	c           client.Client
	serviceName string
}

func NewTraceClient(serviceName string, c client.Client) TraceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "trace"
	}
	return &traceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *traceClient) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Trace.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traceClient) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Trace.Read", in)
	out := new(ReadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Trace.Delete", in)
	out := new(DeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traceClient) Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Trace.Search", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Trace service

type TraceHandler interface {
	Create(context.Context, *CreateRequest, *CreateResponse) error
	Read(context.Context, *ReadRequest, *ReadResponse) error
	Delete(context.Context, *DeleteRequest, *DeleteResponse) error
	Search(context.Context, *SearchRequest, *SearchResponse) error
}

func RegisterTraceHandler(s server.Server, hdlr TraceHandler) {
	s.Handle(s.NewHandler(&Trace{hdlr}))
}

type Trace struct {
	TraceHandler
}

func (h *Trace) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.TraceHandler.Create(ctx, in, out)
}

func (h *Trace) Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error {
	return h.TraceHandler.Read(ctx, in, out)
}

func (h *Trace) Delete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error {
	return h.TraceHandler.Delete(ctx, in, out)
}

func (h *Trace) Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error {
	return h.TraceHandler.Search(ctx, in, out)
}

var fileDescriptor0 = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x91, 0xdf, 0x4e, 0xb3, 0x40,
	0x10, 0xc5, 0xfb, 0x07, 0xfa, 0x7d, 0x4e, 0x0b, 0x35, 0xab, 0x17, 0x58, 0x6f, 0x0c, 0x51, 0x63,
	0x62, 0xba, 0x4d, 0xaa, 0x6f, 0xa0, 0xb7, 0xde, 0xb4, 0xbe, 0xc0, 0x96, 0x0e, 0x2d, 0x09, 0xb0,
	0xb8, 0xbb, 0xed, 0x9b, 0xf9, 0x7e, 0x0e, 0x2c, 0xa4, 0x50, 0x13, 0x6f, 0x48, 0x66, 0xe7, 0x9c,
	0x33, 0x33, 0x3f, 0x60, 0xb9, 0x4b, 0xcc, 0xfe, 0xb0, 0xe1, 0x91, 0xcc, 0x16, 0x59, 0x12, 0x29,
	0xb9, 0x30, 0x4a, 0x44, 0x38, 0xd7, 0xea, 0xb8, 0x28, 0x94, 0x34, 0x75, 0x6d, 0xbf, 0xbc, 0x7a,
	0x99, 0xbd, 0xfe, 0xf2, 0xec, 0xe4, 0xbc, 0x48, 0x85, 0x89, 0xa5, 0xca, 0x6a, 0x7d, 0xcb, 0x6b,
	0x5d, 0xe1, 0x3d, 0x78, 0x6f, 0x0a, 0x85, 0xc1, 0x15, 0x7e, 0x1d, 0x50, 0x1b, 0x76, 0x05, 0x8e,
	0x2e, 0x44, 0x1e, 0xf4, 0xef, 0xfa, 0x4f, 0xe3, 0xa5, 0xcb, 0xd7, 0x54, 0x84, 0x97, 0xe0, 0x37,
	0x2a, 0x5d, 0xc8, 0x5c, 0x63, 0x78, 0x03, 0xe3, 0x15, 0x8a, 0x6d, 0xe3, 0x02, 0x18, 0x24, 0xdb,
	0xca, 0x73, 0x41, 0x91, 0x13, 0xdb, 0xb2, 0x52, 0x76, 0x0d, 0x6e, 0x99, 0xa8, 0xa9, 0x3d, 0x3c,
	0x45, 0xde, 0x82, 0xf7, 0x8e, 0x29, 0x9e, 0x06, 0xb7, 0x23, 0x68, 0x5e, 0xd3, 0xac, 0xe7, 0x7d,
	0x80, 0xb7, 0x46, 0xa1, 0xa2, 0x7d, 0x23, 0x9f, 0x80, 0x93, 0x8b, 0x0c, 0xad, 0x81, 0x79, 0xe0,
	0xa6, 0x49, 0x96, 0x98, 0x60, 0x40, 0xe5, 0x90, 0xf9, 0x30, 0x92, 0x71, 0xac, 0xd1, 0x04, 0xc3,
	0xaa, 0x9e, 0xc2, 0x3f, 0x85, 0x47, 0x54, 0x1a, 0x03, 0x87, 0x1e, 0xfe, 0x87, 0x8f, 0xe0, 0x37,
	0x71, 0x7f, 0x6d, 0xb9, 0xfc, 0xee, 0x83, 0xfb, 0x59, 0xe2, 0x62, 0xcf, 0x30, 0xb2, 0x08, 0x98,
	0xcf, 0x3b, 0xc4, 0x66, 0x53, 0x7e, 0xc6, 0xa6, 0xc7, 0x1e, 0xc0, 0x29, 0x11, 0xb0, 0x09, 0x6f,
	0x41, 0x9a, 0x79, 0xbc, 0xcd, 0x85, 0x64, 0x94, 0x69, 0xcf, 0xa4, 0xcc, 0x0e, 0x0c, 0xca, 0x3c,
	0xbb, 0xbf, 0x12, 0xdb, 0x95, 0x49, 0xdc, 0x41, 0x41, 0xe2, 0xee, 0x2d, 0x61, 0x6f, 0x33, 0xaa,
	0xfe, 0xee, 0xcb, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xab, 0x0d, 0x76, 0xd9, 0x49, 0x02, 0x00,
	0x00,
}
